### ISSUE TITLE
Port-forward not working as expected(?)

### ISSUE THREAD

**Issue by Omritk** [QualiSystemsLab/kubernetes-shell#26]
it might not be an issue at all, as im not 100% sure how the Internal & External ports behave in Kubernetes.

when deploying an App with Internal & External ports (e.g. "Hello minikube") which has port 8080 serving a web page, in the App configuration I set Internal to 8080, external to 20001. after the deployment is done, going to "kubehost:20001" doesnt redirect me to the minikube.
running the command 
kubectl --namespace={CloudShell-NameSpace} port-forward {CloudShell Deployed pod} 20001:8080
will allow me access to the webpage.

**Comment by alexazarh** [comment]
Its probably not behaving as you expected.

Internal ports are open only for traffic inside Kubernetes and external ports are open for traffic from outside. For example, when you define an external port 20001, it will not create mapping to internal ports you specified. It will open port 20001 on each replica and create a mapping of 20001:20001 on the external service.

I am closing this issue.
